config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  get '/show/:id', to: 'flats#show', as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"
class FlatsController < ApplicationController
  def get_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    return JSON.parse(open(url).read)
  end
  def index
    @flats = get_flats
  end

  def show
    @show = get_flats.find{|flat| flat['id'] == params[:id].to_i}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats#index</h1>
<p>Find me in app/views/flats/index.html.erb</p>
<% @flats.each do |flat| %>
  <div>
    <p><%= link_to flat['name'], flat_path(flat['id']) %></p>
    <p><%= flat['price'] %> <%= flat['priceCurrency'] %></p>
  </div>
<% end %>

app/views/flats/show.html.erb
<h1>Flats#show</h1>
<p>Find me in app/views/flats/show.html.erb</p>
  <div>
    <p><%= @show['name'] %></p>
    <p><%= @show['price'] %> <%= @show['priceCurrency'] %></p>
    <img src="<%=@show['imageUrl']%>" alt="" height="200">
    <%= link_to 'back', root_path %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeAirBnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>